### ISSUE TITLE
suggest path "elixir-ls/language_server.sh" to support multiple Language Servers

### ISSUE THREAD

**Issue by louisrawlins** [chipotle/Elixir.bbpackage#1]
https://github.com/chipotle/Elixir.bbpackage/blob/ce4b302354f91d0c54f750be66615ef3fd18ca7f/Contents/Language%20Servers/README#L3
-

Thank you! Your work helped me install the Elixir Language Server successfully on BBEdit.

Suggest a small change to your note in README:

> Note: This folder should contain the contents of the zip file at this level, not a folder containing them!

You can include the path to the server (eg, "elixir-ls/language_server.sh") which would allow you to install multiple Language Servers.

Screenshot below:

![Screen Shot 2023-06-12 at 1 48 39 PM](https://github.com/chipotle/Elixir.bbpackage/assets/188454/593db0db-1546-445f-8762-5beaa1401fbe)

Guidance from Bare Bones Software on placement of Language Server at ~/Library/Application Support/BBEdit/Language Servers/

https://www.barebones.com/support/bbedit/lsp-notes.html#placement

**Comment by chipotle** [comment]
I am adding a note in the top-level README file reminding people about this setting.
